# -- 코드를 입력하세요
# SELECT MCDP_CD AS '진료과 코드', COUNT(MCDP_CD) AS '5월예약건수'
# FROM APPOINTMENT AS A
# WHERE YEAR(A.APNT_YMD)=2022 AND MONTH(A.APNT_YMD)=5
# GROUP BY MCDP_CD
# ORDER BY '5월예약건수','진료과 코드'

SELECT MCDP_CD AS '진료과코드', COUNT(MCDP_CD) AS '5월예약건수' FROM APPOINTMENT
WHERE YEAR(APNT_YMD)=2022 AND MONTH(APNT_YMD) = 5
GROUP BY MCDP_CD
ORDER BY COUNT(MCDP_CD), MCDP_CD